sudo: false
language: C
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_PLAT=linux
         - MATRIX_CC=gcc-4.9 
         - MATRIX_CXX=g++-4.9

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_PLAT=linux
        - MATRIX_CC=gcc-6 
        - MATRIX_CXX=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_PLAT=android

    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_PLAT=osx
    
    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_PLAT=osx

    - os: osx
      env:
        - MATRIX_PLAT=iphoneos

    - os: osx
      env:
        - MATRIX_PLAT=mingw

install:
  - git clone --branch=dev https://github.com/xmake-io/xmake.git tboox/xmake --depth 1
  - cd ./tboox/xmake
  - ./scripts/get.sh __local__
  - cd -
  - if [ "$MATRIX_PLAT" = "android" ]; then
      wget -q https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip;
      unzip -q -o ./android-ndk-r19c-linux-x86_64.zip;
    fi

script:
  - if [ "$MATRIX_PLAT" = "iphoneos" ]; then
      travis_wait 60 xmake l ./scripts/test.lua -D -p iphoneos;
    elif [ "$MATRIX_PLAT" = "mingw" ]; then
      brew install mingw-w64;
      CC="" CXX="" travis_wait 60 xmake l ./scripts/test.lua -D -p mingw;
    elif [ "$MATRIX_PLAT" = "android" ]; then 
      travis_wait 60 xmake l ./scripts/test.lua -D -p android --ndk=`pwd`/android-ndk-r19c;
    elif [ "$MATRIX_PLAT" = "linux" ]; then 
      CC=$MATRIX_CC CXX=$MATRIX_CXX travis_wait 60 xmake l ./scripts/test.lua -D;
    else
      travis_wait 60 xmake l ./scripts/test.lua -D;
    fi
