name: Fedora

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}
    container: fedora:latest

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Fedora-${{ matrix.kind }}
        cancel-in-progress: true
    steps:
      - name: Installation
        run: |
          uname -a
          dnf -y install gfortran p7zip which
          dnf -y install mesa-libGL-devel mesa-libGLU-devel
          dnf -y install @development-tools @rpm-development-tools
          dnf -y install copr-cli make gcc-c++ libatomic libcxx-devel
          dnf -y upgrade git
          dnf -y install perl
          dnf -y install glibc-static libstdc++-static
          git config --global --add safe.directory /__w/xmake-repo/xmake-repo
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: 'fedora'

      - name: Tests
        env:
          XMAKE_ROOT: y
        run: |
          xmake l ./scripts/test.lua -D -k ${{ matrix.kind }} -j4
