name: MingW (Msys2)

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
            { msystem: MINGW64, kind: static, arch: x86_64, prefix: /mingw64 },
            { msystem: MINGW64, kind: shared, arch: x86_64, prefix: /mingw64 },
            { msystem: MINGW32, kind: static, arch: i686,   prefix: /mingw32 },
            { msystem: MINGW32, kind: shared, arch: i686,   prefix: /mingw32 }
        ]

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-MSYS2_MINGW-${{ matrix.msystem }}-${{ matrix.kind }}-${{ matrix.arch }}
        cancel-in-progress: true
    steps:

      - uses: actions/checkout@v1
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: git base-devel unzip p7zip mingw-w64-${{ matrix.arch }}-toolchain mingw-w64-${{ matrix.arch }}-gcc-fortran
          update: true

      - name: Prepare
        shell: msys2 {0}
        run: |
          git clone https://github.com/xmake-io/xmake.git --recurse-submodules -b master
          cd xmake
          ./configure
          make -j4
          make install PREFIX=${{ matrix.prefix }}
          xmake --version
          cd ..
          git reset --hard HEAD
          git clean -fdx

      - name: Tests
        shell: msys2 {0}
        run: |
          if [ "${{ matrix.arch }}" == "x86_64" ]; then
            xmake l ./scripts/test.lua -vD -p mingw -a x86_64 -k ${{ matrix.kind }}
          else
            xmake l ./scripts/test.lua -vD -p mingw -a i386 -k ${{ matrix.kind }}
          fi

