name: Monkey (FreeBSD)

on:
  schedule: # execute every 24 hours
    - cron: "0 */24 * * *"

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-12]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Tests
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          mem: 4096
          copyback: false
          prepare: pkg install -y git curl unzip gmake llvm gsed bash perl5
          run: |
            git clone --recurse-submodules https://github.com/xmake-io/xmake.git /tmp/xmake -b dev
            cd /tmp/xmake
            ./configure
            gmake -j4
            gmake install
            export XMAKE_ROOT=y
            git clone https://github.com/xmake-io/xmake-repo.git /tmp/xmake-repo -b dev --depth 2
            cd /tmp/xmake-repo
            xmake l ./scripts/monkey.lua -D -k ${{ matrix.kind }}


